name: BBRL-Lobby-System
main: com.example.bbrl.Main
version: 3.1
api-version: "1.20"
depend: [TimingSystem]
description: A lobby system made for the Builders and Boaters Racing Server - now with GUI voting!
author: BoshyWashy and allied_galaxy7

commands:
  votejoin:
    description: Join the voting lobby
    usage: /votejoin
    permission: bbrl.join

  voteleave:
    description: Leave the voting lobby
    usage: /voteleave
    permission: bbrl.join

  vote:
    description: Open vote menu or vote by name
    usage: /vote [track]
    permission: bbrl.vote

  votelobby:
    description: Admin command to control voting
    usage: /votelobby <open|close|start|reopen|debug>
    permission: bbrl.admin

  votetrack:
    description: Add/remove tracks or set their item
    usage: /votetrack <add|remove|item> ...
    permission: bbrl.admin

  voterace:
    description: Join the current lobby-owned race heat
    usage: /voterace
    permission: bbrl.join

permissions:
  bbrl.admin:
    default: op
  bbrl.join:
    default: true
  bbrl.vote:
    default: true
